#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApp.Resource", IsApplication=true)]

namespace AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int black = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int defaultBackground = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int defaultTextColor = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int editTextColor = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btnSend = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logoBig = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int resetBtn = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int imageView1 = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int menu_addDevice = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int pairedDeviceLayout = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int pairedDeviceNameTxt = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int pairedDevicesSpinner = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int powerTextView = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int resetBtn = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int seekBar1 = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int sendBtn = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int timeEditText = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddNew = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int pairedDeviceAdapter = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int topMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ActionBar = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ActionBar_Title = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
